name: artnext
description: Find your local art events!

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+18

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0        # cached image, better performance
  shared_preferences:                 # allow access to localstorage (first launch info)
  firebase_database: ^7.1.2           # firebase access
  firebase_core: "^1.3.0"             # firebase access
  firebase_auth: "^3.0.2"             # firebase Authentication
  cloud_firestore: "^2.3.0"           # firebase Firestore
  provider: "^6.0.0"                  # allow object sharing through Context
  datetime_picker_formfield: ^2.0.0   # datetime picker plugin
  intl: ^0.17.0                       # plugin about internationalization
  google_fonts: ^2.1.0                # allow google Fonts usage
  font_awesome_flutter: ^9.1.0        # nice pictograms
  mailto:                             # allows sending email
  url_launcher:                       # opens link
  share_plus: ^2.1.4                  # share functionnality
  introduction_screen: ^2.1.0         # display image at the beginning

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/github.png
  - assets/images/placeholder.jpg
  - assets/images/testonboarding.jpg
  - assets/images/profil.png
  - assets/images/schedule.png
  - assets/images/listattendees.png
  - assets/images/listevent.png
  - assets/images/searchevent.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: RichieBrusher
       fonts:
         - asset: fonts/RichieBrusher-l2yy.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
